[workspace]
resolver = "3"
members = ["rndk", "ndk-examples", "cargo-rapk"]

[workspace.package]
version = "0.14.0"
edition = "2024"

[workspace.dependencies]
rndk = { version = "0.14.0", path = "rndk" }
